<div style="font-family:Arial;">

<h1 style="color:#004aad; text-align:center; font-size:42px; margin-bottom:10px;">
  PROJET DE MACHINE LEARNING
</h1>


<div style="border:2px solid #b00000; padding:14px; border-radius:10px; text-align:center; width:80%; margin:auto;">
  <span style="font-size:34px; font-weight:bold; color:#7a0000;">
    HOUSE PRICES PREDICTION
  </span>
</div>
<h3 style="color:#004aad; text-align:center; font-size:35px; margin-bottom:10px;">
  CLEANING 
</h3>

<p style="margin-top:25px; font-size:18px;">
  <b>Réalisé par :</b><br>
  • Compaoré BASSIROU<br>
  • Samba DIENG<br>
  • Yves Mistalengar DJERAKEI <br>
  • Divana KERENCIA<br>
  • Ange Emilson RAYAN<br>
</p>

<p style="margin-top:10px; font-size:15px;">
    Objectif du notebook <br>
Ce notebook a pour objectif de réaliser un audit initial et un nettoyage structurel des données du jeu House Prices.
À ce stade, il s’agit uniquement de comprendre la structure de la base, la nature des variables et la présence éventuelle de valeurs manquantes ou incohérentes.
Aucune transformation destinée à la modélisation (encodage, imputation statistique, normalisation) n’est réalisée dans cette première partie.
</p>
</div>

In [1]:
# Importation des bibliothèques nécessaires pour le traitement des données
from pathlib import Path  # Gestion des chemins de fichiers de manière portable
import pandas as pd       # Manipulation et analyse de données structurées
import numpy as np        # Calculs numériques et opérations sur tableaux

In [2]:
# Configuration de l'affichage pandas pour une meilleure visibilité des données
pd.set_option("display.max_columns", None)  # Afficher toutes les colonnes
pd.set_option("display.max_rows", 200)       # Limiter l'affichage à 200 lignes

In [40]:
# Configuration du répertoire de travail du projet
# Cette section permet de définir automatiquement le chemin racine du projet
# de manière portable, indépendamment de l'environnement d'exécution

import os
from pathlib import Path

# Détection automatique du répertoire racine du projet
# Stratégie : identifier si l'exécution se fait depuis un script ou un notebook
try:
    # Cas d'un script Python : utilisation de __file__ pour localiser le projet
    project_root = Path(__file__).resolve().parent.parent
except NameError:
    # Cas d'un notebook Jupyter : détection basée sur le répertoire courant
    current_dir = Path.cwd()
    # Si l'exécution se fait depuis le dossier notebooks/, remonter d'un niveau
    if current_dir.name == "notebooks":
        project_root = current_dir.parent
    else:
        # Si déjà à la racine, conserver le répertoire courant
        project_root = current_dir

# Définir le répertoire de travail à la racine du projet
# Cela garantit que les chemins relatifs fonctionnent correctement
os.chdir(project_root)
print(f"Répertoire de travail : {os.getcwd()}")

Répertoire de travail : C:\Users\pc\Desktop\ISE2 2024\MACHINE LEARNING\ProjetMachine-Learning-House-prices-prediction

In [4]:
# Chargement des jeux de données brutes depuis le répertoire data/raw
# Les chemins sont relatifs au répertoire racine du projet défini précédemment
train = pd.read_csv("data/raw/train.csv")              # Jeu d'entraînement avec variable cible
test  = pd.read_csv("data/raw/test.csv")                # Jeu de test sans variable cible
sample = pd.read_csv("data/raw/sample_submission.csv") # Format de soumission attendu

In [5]:
train.shape

(1460, 81)

In [6]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [8]:
print("Train shape:", train.shape)
print("Test shape :", test.shape)
print("SalePrice in train?", "SalePrice" in train.columns)
print("SalePrice in test ?", "SalePrice" in test.columns)

Train shape: (1460, 81)
Test shape : (1459, 80)
SalePrice in train? True
SalePrice in test ? False

## 1) Audit des valeurs manquantes (NA)

Objectif :
- Identifier les variables contenant des valeurs manquantes dans le jeu **train**
- Comprendre la nature des NA :
  - **NA structurels** : absence réelle d’un équipement (piscine, garage, sous-sol…)
  - **NA non structurels** : information attendue mais manquante (ex : LotFrontage)

Dans cette étape, on ne fait PAS encore :
- d’imputation statistique (médiane, KNN, modèles…)
- d’encodage (one-hot, ordinal encoding…)
- de normalisation / scaling

On fait uniquement un nettoyage "métier" des NA structurels.

OCCUPONS NOUS D'ABORD DE LA BASE TRAIN VU QUE ELLE ET LA BASE TEST PEUVENT SE COMPORTER DIFFEREMMENT AVEC LES VARIABLES A NA

In [9]:
# Audit initial des valeurs manquantes dans le jeu d'entraînement
# Objectif : identifier toutes les variables contenant au moins une valeur manquante

# Calcul du nombre de valeurs manquantes par variable
na_counts = train.isna().sum()

# Filtrage : ne conserver que les variables avec au moins une valeur manquante
# Tri décroissant pour identifier les variables les plus problématiques
na_counts_nonzero = na_counts[na_counts > 0].sort_values(ascending=False)

print(f"Nombre de variables avec au moins 1 NA : {na_counts_nonzero.shape[0]}")
na_counts_nonzero

Nombre de variables avec au moins 1 NA : 19

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtExposure      38
BsmtFinType2      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
dtype: int64

In [10]:
# Calcul du pourcentage de valeurs manquantes par variable
# Cette métrique permet d'évaluer l'ampleur du problème pour chaque variable
na_percent = (na_counts_nonzero / len(train) * 100).round(2)

# Création d'un tableau récapitulatif combinant nombre et pourcentage de NA
# Tri par nombre de valeurs manquantes décroissant pour faciliter l'analyse
na_summary = (
    pd.DataFrame({"na_count": na_counts_nonzero, "na_percent": na_percent})
    .sort_values("na_count", ascending=False)
)

na_summary

              na_count  na_percent
PoolQC            1453       99.52
MiscFeature       1406       96.30
Alley             1369       93.77
Fence             1179       80.75
MasVnrType         872       59.73
FireplaceQu        690       47.26
LotFrontage        259       17.74
GarageType          81        5.55
GarageYrBlt         81        5.55
GarageFinish        81        5.55
GarageQual          81        5.55
GarageCond          81        5.55
BsmtExposure        38        2.60
BsmtFinType2        38        2.60
BsmtQual            37        2.53
BsmtCond            37        2.53
BsmtFinType1        37        2.53
MasVnrArea           8        0.55
Electrical           1        0.07

Une fois qu'on a la liste des variables ayant des NA, on va détecter dans cette liste les NA structurels (les NA qui le sont du fait de l'absence de matériel)

In [11]:
# Identification des variables à valeurs manquantes structurelles
# Les NA structurels représentent l'absence réelle d'un équipement ou d'une caractéristique
# (exemple : pas de piscine, pas de garage, pas de sous-sol)
# Ces valeurs manquantes ne sont pas des erreurs mais des informations valides

na_structural_vars = [
    "PoolQC", "MiscFeature", "Alley", "Fence",
    "FireplaceQu",
    "GarageType", "GarageYrBlt", "GarageFinish", "GarageQual", "GarageCond",
    "BsmtExposure", "BsmtFinType2", "BsmtQual", "BsmtCond", "BsmtFinType1", "MasVnrType"
]
# Note : MasVnrType est une variable à NA structurels mais son traitement est reporté
# car elle est liée à MasVnrArea qui nécessite un traitement spécifique

# Vérification de cohérence : contrôle que toutes les variables sont correctement classées
missing_in_list = set(na_summary.index) - set(na_structural_vars)  # Variables avec NA non classées comme structurelles
extra_in_list = set(na_structural_vars) - set(na_summary.index)    # Variables classées structurelles mais sans NA dans train

print("NA présents mais NON classés structurels :", sorted(missing_in_list))
print("Classés structurels mais sans NA dans train :", sorted(extra_in_list))

NA présents mais NON classés structurels : ['Electrical', 'LotFrontage', 'MasVnrArea']
Classés structurels mais sans NA dans train : []

In [12]:
# Identification des variables à valeurs manquantes non structurelles
# Les NA non structurels représentent des informations attendues mais manquantes
# Ces valeurs nécessitent une imputation statistique (médiane, mode, etc.)
na_non_structural_vars = sorted(list(missing_in_list))

na_non_structural_vars

['Electrical', 'LotFrontage', 'MasVnrArea']

In [13]:
# Séparation des variables structurelles en qualitatives et numériques
# Les variables qualitatives structurelles seront remplacées par "None" (chaîne de caractères)
# Les variables numériques structurelles nécessitent un traitement spécifique

na_structural_cat = [v for v in na_structural_vars if v != "GarageYrBlt"]

# Cas particulier : GarageYrBlt est une variable numérique structurelle
# Son traitement sera effectué séparément avec création d'un indicateur binaire
print("NA structurels qualitatifs :", na_structural_cat)
print("NA structurel numérique (à part) :", ["GarageYrBlt"])

NA structurels qualitatifs : ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'BsmtExposure', 'BsmtFinType2', 'BsmtQual', 'BsmtCond', 'BsmtFinType1', 'MasVnrType']
NA structurel numérique (à part) : ['GarageYrBlt']

In [14]:
# Création d'une copie du jeu d'entraînement pour le nettoyage
# Important : ne jamais modifier directement les données brutes pour préserver l'intégrité des données originales
train_clean = train.copy()

# =========================
# Traitement des valeurs manquantes structurelles qualitatives
# =========================
# Remplacement des NA structurels par la chaîne "None" pour indiquer explicitement l'absence
# Cette approche transforme les valeurs manquantes en modalité catégorielle valide
for col in na_structural_cat:
    train_clean[col] = train_clean[col].fillna("None")

# Vérification : contrôle qu'il ne reste plus de valeurs manquantes sur ces colonnes
train_clean[na_structural_cat].isna().sum().sort_values(ascending=False).head(10)

PoolQC          0
MiscFeature     0
Alley           0
Fence           0
FireplaceQu     0
GarageType      0
GarageFinish    0
GarageQual      0
GarageCond      0
BsmtExposure    0
dtype: int64

In [15]:
# =========================
# Vérification : confirmation que "None" est bien devenu une modalité valide
# =========================
# Cette vérification permet de s'assurer que le remplacement des NA par "None"
# a bien fonctionné et que "None" apparaît comme une catégorie dans les distributions
cols_check = ["PoolQC", "Fence", "GarageType", "BsmtQual"]
for c in cols_check:
    if c in train_clean.columns:
        print(f"\n{c}")
        print(train_clean[c].value_counts(dropna=False).head(10))

PoolQC
PoolQC
None    1453
Gd         3
Ex         2
Fa         2
Name: count, dtype: int64

Fence
Fence
None     1179
MnPrv     157
GdPrv      59
GdWo       54
MnWw       11
Name: count, dtype: int64

GarageType
GarageType
Attchd     870
Detchd     387
BuiltIn     88
None        81
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

BsmtQual
BsmtQual
TA      649
Gd      618
Ex      121
None     37
Fa       35
Name: count, dtype: int64

In [16]:
# =========================
# État des valeurs manquantes après traitement des NA structurels
# =========================
# Identification des variables qui contiennent encore des valeurs manquantes
# après le traitement des NA structurels qualitatifs
na_counts = train_clean.isna().sum()
na_counts[na_counts > 0].sort_values(ascending=False)

LotFrontage    259
GarageYrBlt     81
MasVnrArea       8
Electrical       1
dtype: int64

In [17]:
# =========================
# Traitement de MasVnrArea (surface du parement en maçonnerie)
# =========================
# MasVnrType : type de parement (BrkFace, Stone, etc.) - variable qualitative
# MasVnrArea : surface du parement - variable numérique
# Relation logique : si MasVnrType est "None" (pas de parement), alors MasVnrArea doit être 0
# Imputation : remplacer les NA de MasVnrArea par 0 (cohérent avec l'absence de parement)

if "MasVnrArea" in train_clean.columns:
    train_clean["MasVnrArea"] = train_clean["MasVnrArea"].fillna(0)

# Vérification de cohérence entre MasVnrType et MasVnrArea
train_clean[["MasVnrType", "MasVnrArea"]].isna().sum()

MasVnrType    0
MasVnrArea    0
dtype: int64

In [18]:
# =========================
# Imputation de la variable Electrical
# =========================
# Variable non structurelle avec une seule valeur manquante
# Stratégie : imputation par la modalité la plus fréquente (mode)
# Cette approche est appropriée pour une variable catégorielle avec très peu de valeurs manquantes

if "Electrical" in train_clean.columns:
    mode_elec = train_clean["Electrical"].mode()[0]
    train_clean["Electrical"] = train_clean["Electrical"].fillna(mode_elec)

    print("Mode utilisé pour Electrical :", mode_elec)
    print("NA restants Electrical :", train_clean["Electrical"].isna().sum())

Mode utilisé pour Electrical : SBrkr
NA restants Electrical : 0

In [19]:
# =========================
# Traitement de GarageYrBlt (année de construction du garage)
# =========================
# Variable numérique structurelle nécessitant un traitement en deux étapes :
# 1. Création d'un indicateur binaire pour distinguer présence/absence de garage
# 2. Imputation conditionnelle selon la présence ou l'absence de garage

# Création de l'indicateur binaire HasGarage
# Valeur 1 si garage présent, 0 sinon
train_clean["HasGarage"] = (train_clean["GarageType"] != "None").astype(int)

# Imputation conditionnelle de GarageYrBlt
if "GarageYrBlt" in train_clean.columns:
    # Cas 1 : pas de garage -> valeur sentinelle 0
    train_clean.loc[train_clean["HasGarage"] == 0, "GarageYrBlt"] = train_clean.loc[train_clean["HasGarage"] == 0, "GarageYrBlt"].fillna(0)

    # Cas 2 : garage présent mais année manquante -> médiane des maisons avec garage
    # Cette imputation est plus réaliste que la médiane globale
    median_garage_year = train_clean.loc[train_clean["HasGarage"] == 1, "GarageYrBlt"].median()
    train_clean.loc[train_clean["HasGarage"] == 1, "GarageYrBlt"] = train_clean.loc[train_clean["HasGarage"] == 1, "GarageYrBlt"].fillna(median_garage_year)

    print("Médiane GarageYrBlt (maisons avec garage) :", median_garage_year)
    print("NA restants GarageYrBlt :", train_clean["GarageYrBlt"].isna().sum())

Médiane GarageYrBlt (maisons avec garage) : 1980.0
NA restants GarageYrBlt : 0

In [20]:
# =========================
# Imputation de LotFrontage (largeur de façade du lot)
# =========================
# Variable non structurelle : information attendue mais manquante
# Stratégie : imputation hiérarchique par quartier (Neighborhood)
# Justification : la largeur de façade est corrélée au quartier (zones résidentielles similaires)

if "LotFrontage" in train_clean.columns and "Neighborhood" in train_clean.columns:
    # Étape 1 : imputation par la médiane du quartier
    # Cette approche préserve la cohérence spatiale des données
    train_clean["LotFrontage"] = train_clean["LotFrontage"].fillna(
        train_clean.groupby("Neighborhood")["LotFrontage"].transform("median")
    )
    # Étape 2 : fallback sur la médiane globale pour les cas où le quartier n'a pas de données
    # Cette étape garantit qu'aucune valeur manquante ne subsiste
    train_clean["LotFrontage"] = train_clean["LotFrontage"].fillna(train_clean["LotFrontage"].median())

    print("NA restants LotFrontage :", train_clean["LotFrontage"].isna().sum())

NA restants LotFrontage : 0

In [21]:
# =========================
# Contrôle final : vérification de l'absence de valeurs manquantes
# =========================
# Cette vérification confirme que tous les traitements ont été effectués correctement
# et qu'aucune valeur manquante ne subsiste dans le jeu d'entraînement nettoyé
na_final = train_clean.isna().sum()
na_final[na_final > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [22]:
## Traitement des valeurs manquantes dans le jeu de test
# =====================================================
# Le jeu de test peut présenter des valeurs manquantes différentes du jeu d'entraînement
# Il est essentiel d'appliquer les mêmes stratégies de traitement pour garantir la cohérence

# Audit initial des valeurs manquantes dans le jeu de test
na_counts_test = test.isna().sum()

# Identification des variables avec au moins une valeur manquante
na_counts_nonzero_test = na_counts_test[na_counts_test > 0].sort_values(ascending=False)

print(f"Nombre de variables avec au moins 1 NA : {na_counts_nonzero_test.shape[0]}")
na_counts_nonzero_test

Nombre de variables avec au moins 1 NA : 33

PoolQC          1456
MiscFeature     1408
Alley           1352
Fence           1169
MasVnrType       894
FireplaceQu      730
LotFrontage      227
GarageQual        78
GarageCond        78
GarageYrBlt       78
GarageFinish      78
GarageType        76
BsmtCond          45
BsmtQual          44
BsmtExposure      44
BsmtFinType1      42
BsmtFinType2      42
MasVnrArea        15
MSZoning           4
Functional         2
BsmtFullBath       2
Utilities          2
BsmtHalfBath       2
Exterior1st        1
Exterior2nd        1
TotalBsmtSF        1
BsmtUnfSF          1
BsmtFinSF2         1
BsmtFinSF1         1
KitchenQual        1
GarageArea         1
GarageCars         1
SaleType           1
dtype: int64

In [23]:
# Calcul du pourcentage de valeurs manquantes dans le jeu de test
# Note : le dénominateur utilise len(train) pour permettre la comparaison avec le jeu d'entraînement
na_percent_test = (na_counts_nonzero_test / len(train) * 100).round(2)

# Création d'un tableau récapitulatif pour le jeu de test
na_summary_test = (
    pd.DataFrame({"na_count": na_counts_nonzero_test, "na_percent": na_percent_test})
    .sort_values("na_count", ascending=False)
)

na_summary_test

              na_count  na_percent
PoolQC            1456       99.73
MiscFeature       1408       96.44
Alley             1352       92.60
Fence             1169       80.07
MasVnrType         894       61.23
FireplaceQu        730       50.00
LotFrontage        227       15.55
GarageQual          78        5.34
GarageCond          78        5.34
GarageYrBlt         78        5.34
GarageFinish        78        5.34
GarageType          76        5.21
BsmtCond            45        3.08
BsmtQual            44        3.01
BsmtExposure        44        3.01
BsmtFinType1        42        2.88
BsmtFinType2        42        2.88
MasVnrArea          15        1.03
MSZoning             4        0.27
Functional           2        0.14
BsmtFullBath         2        0.14
Utilities            2        0.14
BsmtHalfBath         2        0.14
Exterior1st          1        0.07
Exterior2nd          1        0.07
TotalBsmtSF          1        0.07
BsmtUnfSF            1        0.07
BsmtFinSF2           1        0.07
BsmtFinSF1           1        0.07
KitchenQual          1        0.07
GarageArea           1        0.07
GarageCars           1        0.07
SaleType             1        0.07

In [24]:
# ============================
# Classification des variables pour le traitement du jeu de test
# ============================
# Cette classification permet d'appliquer les mêmes stratégies de traitement
# que celles utilisées pour le jeu d'entraînement, garantissant la cohérence

# Variables structurelles d'existence (qualitatives principales)
# Ces variables indiquent la présence ou l'absence d'un équipement
structural_exist_vars = [
    "PoolQC",        # Piscine
    "MiscFeature",  # Équipements divers
    "Alley",         # Accès / extérieur
    "Fence",         # Clôture
    "FireplaceQu",   # Cheminée
    "GarageType",    # Garage
    "BsmtQual",      # Sous-sol
    "MasVnrType"     # Parement
]

# Variables structurelles qualitatives dépendantes
# Ces variables décrivent des caractéristiques d'équipements existants
structural_qual_dependent_vars = [
    "GarageFinish",  # Garage
    "GarageQual",    # Garage
    "GarageCond",    # Garage
    "BsmtCond",      # Sous-sol
    "BsmtExposure",  # Sous-sol
    "BsmtFinType1",  # Sous-sol
    "BsmtFinType2"   # Sous-sol
]

# Variables structurelles numériques dépendantes
# Ces variables quantifient des caractéristiques d'équipements existants
structural_num_dependent_vars = [
    "GarageYrBlt",   # Garage
    "GarageArea",    # Garage
    "GarageCars",    # Garage
    "TotalBsmtSF",   # Sous-sol
    "BsmtUnfSF",     # Sous-sol
    "BsmtFinSF1",    # Sous-sol
    "BsmtFinSF2",    # Sous-sol
    "BsmtFullBath",  # Sous-sol
    "BsmtHalfBath",  # Sous-sol
    "MasVnrArea"     # Parement
]

# Variables non structurelles
# Ces variables nécessitent une imputation statistique
non_structural_vars = [
    "LotFrontage",
    "Electrical",
    "MSZoning",
    "Functional",
    "Utilities",
    "Exterior1st",
    "Exterior2nd",
    "KitchenQual",
    "SaleType"
]

In [25]:
# Création d'une copie du jeu de test pour le nettoyage
# Important : préserver l'intégrité des données brutes en travaillant sur une copie
test_clean = test.copy()

In [26]:
# ============================
# B) Variables structurelles d’existence
# ============================

for col in structural_exist_vars:
    if col in test_clean.columns:
        test_clean[col] = test_clean[col].fillna("None")

In [27]:
# ============================
# Traitement des variables structurelles qualitatives dépendantes
# ============================
# Remplacement des valeurs manquantes par "None" pour les caractéristiques d'équipements absents
# Ces variables dépendent des variables d'existence traitées précédemment

for col in structural_qual_dependent_vars:
    if col in test_clean.columns:
        test_clean[col] = test_clean[col].fillna("None")

In [28]:
# ============================
# D1) Indicateurs d’existence
# ============================

# Garage
test_clean["HasGarage"] = (test_clean["GarageType"] != "None").astype(int)

# Sous-sol
test_clean["HasBsmt"] = (test_clean["BsmtQual"] != "None").astype(int)

# Parement
test_clean["HasMasVnr"] = (test_clean["MasVnrType"] != "None").astype(int)

In [29]:
# ============================
# Imputations conditionnelles des variables numériques dépendantes
# ============================
# Principe : si l'équipement est absent, les variables numériques associées sont mises à 0
# Cette approche garantit la cohérence logique entre les variables qualitatives et numériques

# Variables numériques liées au garage
garage_num_vars = ["GarageYrBlt", "GarageArea", "GarageCars"]
for col in garage_num_vars:
    if col in test_clean.columns:
        # Si pas de garage, mettre les valeurs numériques à 0
        test_clean.loc[test_clean["HasGarage"] == 0, col] = 0

# Variables numériques liées au sous-sol
bsmt_num_vars = [
    "TotalBsmtSF", "BsmtUnfSF", "BsmtFinSF1", "BsmtFinSF2",
    "BsmtFullBath", "BsmtHalfBath"
]
for col in bsmt_num_vars:
    if col in test_clean.columns:
        # Si pas de sous-sol, mettre les valeurs numériques à 0
        test_clean.loc[test_clean["HasBsmt"] == 0, col] = 0

# Variable numérique liée au parement
if "MasVnrArea" in test_clean.columns:
    # Si pas de parement, mettre la surface à 0
    test_clean.loc[test_clean["HasMasVnr"] == 0, "MasVnrArea"] = 0

In [30]:
# ============================
# Imputation de GarageYrBlt pour les garages existants avec année manquante
# ============================
# Cas particulier : garage présent mais année de construction manquante
# Stratégie : utiliser la médiane calculée sur le jeu d'entraînement
# Cette approche garantit la cohérence entre train et test

if "GarageYrBlt" in test_clean.columns:
    test_clean.loc[
        (test_clean["HasGarage"] == 1) & (test_clean["GarageYrBlt"].isna()),
        "GarageYrBlt"
    ] = median_garage_year  # Médiane calculée sur le jeu d'entraînement

In [31]:
# ============================
# Vérification 1 : État des valeurs manquantes après traitement structurel
# ============================
# Cette vérification permet d'identifier les variables nécessitant encore un traitement
# et de quantifier l'ampleur du travail restant

na_total = test_clean.isna().sum().sum()
print("Nombre TOTAL de valeurs manquantes (NA) dans test_clean :", na_total)

na_by_col = test_clean.isna().sum()
na_cols = na_by_col[na_by_col > 0].sort_values(ascending=False)

print("\nNombre de colonnes avec au moins 1 NA :", na_cols.shape[0])
na_cols

Nombre TOTAL de valeurs manquantes (NA) dans test_clean : 241

Nombre de colonnes avec au moins 1 NA : 10

LotFrontage    227
MSZoning         4
Utilities        2
Functional       2
Exterior2nd      1
Exterior1st      1
KitchenQual      1
GarageCars       1
GarageArea       1
SaleType         1
dtype: int64

In [32]:
# ============================
# Vérification 2 : Comparaison avant/après traitement structurel
# ============================
# Cette analyse permet d'évaluer l'efficacité du traitement et d'identifier
# les variables qui nécessitent encore une imputation non structurelle

na_after = test_clean.isna().sum()
before_cols = set(na_counts_nonzero_test.index)  # Variables avec NA avant traitement
after_cols  = set(na_after[na_after > 0].index) # Variables avec NA après traitement

print("Colonnes qui avaient des NA avant :", len(before_cols))
print("Colonnes qui ont encore des NA après :", len(after_cols))

print("\n NA réglés (présents avant, absents après) :", sorted(list(before_cols - after_cols)))
print("NA restants (encore après nettoyage) :", sorted(list(after_cols)))

Colonnes qui avaient des NA avant : 33
Colonnes qui ont encore des NA après : 10

 NA réglés (présents avant, absents après) : ['Alley', 'BsmtCond', 'BsmtExposure', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtFinType1', 'BsmtFinType2', 'BsmtFullBath', 'BsmtHalfBath', 'BsmtQual', 'BsmtUnfSF', 'Fence', 'FireplaceQu', 'GarageCond', 'GarageFinish', 'GarageQual', 'GarageType', 'GarageYrBlt', 'MasVnrArea', 'MasVnrType', 'MiscFeature', 'PoolQC', 'TotalBsmtSF']
NA restants (encore après nettoyage) : ['Exterior1st', 'Exterior2nd', 'Functional', 'GarageArea', 'GarageCars', 'KitchenQual', 'LotFrontage', 'MSZoning', 'SaleType', 'Utilities']

In [33]:
# ============================
# Vérification 3 : Confirmation de la présence de "None" comme modalité
# ============================
# Cette vérification permet de s'assurer que le remplacement des NA structurels
# par "None" a bien fonctionné et que "None" apparaît dans les distributions

cols_check = ["PoolQC", "Fence", "GarageType", "BsmtQual", "MasVnrType"]
for c in cols_check:
    if c in test_clean.columns:
        print(f"\n--- {c} ---")
        print("NA :", test_clean[c].isna().sum())
        print(test_clean[c].value_counts(dropna=False).head(10))

--- PoolQC ---
NA : 0
PoolQC
None    1456
Ex         2
Gd         1
Name: count, dtype: int64

--- Fence ---
NA : 0
Fence
None     1169
MnPrv     172
GdPrv      59
GdWo       58
MnWw        1
Name: count, dtype: int64

--- GarageType ---
NA : 0
GarageType
Attchd     853
Detchd     392
BuiltIn     98
None        76
Basment     17
2Types      17
CarPort      6
Name: count, dtype: int64

--- BsmtQual ---
NA : 0
BsmtQual
TA      634
Gd      591
Ex      137
Fa       53
None     44
Name: count, dtype: int64

--- MasVnrType ---
NA : 0
MasVnrType
None       894
BrkFace    434
Stone      121
BrkCmn      10
Name: count, dtype: int64

In [34]:
# ============================
# Vérification 4 : Cohérence logique entre MasVnrType et MasVnrArea
# ============================
# Cette vérification permet de détecter d'éventuelles incohérences logiques :
# - MasVnrType = "None" mais MasVnrArea > 0 (incohérence)
# - MasVnrType != "None" mais MasVnrArea = 0 (possible mais à vérifier)

if "MasVnrType" in test_clean.columns and "MasVnrArea" in test_clean.columns:
    print("NA MasVnrType :", test_clean["MasVnrType"].isna().sum())
    print("NA MasVnrArea :", test_clean["MasVnrArea"].isna().sum())

    # Détection des incohérences potentielles
    incoh_1 = test_clean[(test_clean["MasVnrType"] == "None") & (test_clean["MasVnrArea"] > 0)].shape[0]
    incoh_2 = test_clean[(test_clean["MasVnrType"] != "None") & (test_clean["MasVnrArea"] == 0)].shape[0]

NA MasVnrType : 0
NA MasVnrArea : 0

In [35]:
# ============================
# Imputation des valeurs manquantes non structurelles dans le jeu de test
# ============================
# Stratégie : utiliser les statistiques calculées sur le jeu d'entraînement
# pour garantir la cohérence et éviter le data leakage

# A) Variables qualitatives : imputation par le mode du jeu d'entraînement
cat_non_structural = [
    "MSZoning",
    "Utilities",
    "Functional",
    "Exterior1st",
    "Exterior2nd",
    "KitchenQual",
    "SaleType"
]

for col in cat_non_structural:
    if col in test_clean.columns:
        # Utiliser le mode du jeu d'entraînement pour l'imputation
        mode_col = train_clean[col].mode()[0]
        test_clean[col] = test_clean[col].fillna(mode_col)

# B) Variables numériques : imputation conditionnelle pour les garages existants
# Cas : garage présent mais information manquante (rare mais possible)
num_non_structural = ["GarageCars", "GarageArea"]

for col in num_non_structural:
    if col in test_clean.columns:
        # Utiliser la médiane des maisons avec garage du jeu d'entraînement
        median_col = train_clean.loc[train_clean["HasGarage"] == 1, col].median()
        test_clean[col] = test_clean[col].fillna(median_col)

In [36]:
# ============================
# Contrôle final : vérification de l'absence de valeurs manquantes dans le jeu de test
# ============================
# Cette vérification confirme que tous les traitements ont été effectués correctement
# et qu'aucune valeur manquante ne subsiste dans le jeu de test nettoyé

na_final_test = test_clean.isna().sum()
na_final_test[na_final_test > 0]

LotFrontage    227
dtype: int64

In [39]:
# ============================
# Sauvegarde des données nettoyées
# ============================
# Les données nettoyées sont sauvegardées dans le répertoire data/processed
# pour être utilisées dans les étapes suivantes du pipeline (feature engineering, modélisation)

import os

# Création du répertoire de sortie s'il n'existe pas
os.makedirs("data/processed", exist_ok=True)

# Sauvegarde des jeux de données nettoyés au format CSV
# Format CSV choisi pour sa compatibilité avec Kaggle et sa simplicité d'utilisation
train_clean.to_csv("data/processed/train_clean.csv", index=False)
test_clean.to_csv("data/processed/test_clean.csv", index=False)

print(" Fichiers enregistrés :")
print(" - data/processed/train_clean.csv")
print(" - data/processed/test_clean.csv")

 Fichiers enregistrés :
 - data/processed/train_clean.csv
 - data/processed/test_clean.csv